// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: order_list.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ListOrderServiceClient is the client API for ListOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListOrderServiceClient interface {
	ListOrder(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*OrderList, error)
}

type listOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListOrderServiceClient(cc grpc.ClientConnInterface) ListOrderServiceClient {
	return &listOrderServiceClient{cc}
}

func (c *listOrderServiceClient) ListOrder(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*OrderList, error) {
	out := new(OrderList)
	err := c.cc.Invoke(ctx, "/pb.ListOrderService/ListOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ListOrderServiceServer is the server API for ListOrderService service.
// All implementations must embed UnimplementedListOrderServiceServer
// for forward compatibility
type ListOrderServiceServer interface {
	ListOrder(context.Context, *Blank) (*OrderList, error)
	mustEmbedUnimplementedListOrderServiceServer()
}

// UnimplementedListOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedListOrderServiceServer struct {
}

func (UnimplementedListOrderServiceServer) ListOrder(context.Context, *Blank) (*OrderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrder not implemented")
}
func (UnimplementedListOrderServiceServer) mustEmbedUnimplementedListOrderServiceServer() {}

// UnsafeListOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListOrderServiceServer will
// result in compilation errors.
type UnsafeListOrderServiceServer interface {
	mustEmbedUnimplementedListOrderServiceServer()
}

func RegisterListOrderServiceServer(s grpc.ServiceRegistrar, srv ListOrderServiceServer) {
	s.RegisterService(&ListOrderService_ServiceDesc, srv)
}

func _ListOrderService_ListOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListOrderServiceServer).ListOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ListOrderService/ListOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListOrderServiceServer).ListOrder(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

// ListOrderService_ServiceDesc is the grpc.ServiceDesc for ListOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ListOrderService",
	HandlerType: (*ListOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOrder",
			Handler:    _ListOrderService_ListOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_list.proto",
}
